const fs = require('fs');
const content = fs.readFileSync('e:/AntigravitiProgetti/CompendioTheWitcher/TO DO/report_lore_compendio.md', 'utf8');
const lines = content.split('\n');
console.log("Total lines in file:", lines.length);
console.log("File size in bytes:", content.length);
console.log("First 20 lines:");
console.log(lines.slice(0, 20).join('\n'));
console.log("------------------------");
console.log("Last 40 lines:");
console.log(lines.slice(-40).join('\n'));
