import os
import re

scratch_dir = r"e:\AntigravitiProgetti\CompendioTheWitcher\scratch"

# Nuovi prompt forniti dall'utente
new_prompts_data = {
    54: [
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Tuono di Alzur spell, a massive devastating bolt of pure crackling blue lightning striking a single point with violent energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Vortice Fiammeggiante spell, a violent swirling tornado of roaring orange and crimson arcane fire, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Zefiro spell, a gentle and controlled swirling vortex of pale white wind magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Acuire Sensi spell, a subtle pulsing aura of pale blue magic enhancing a pair of ethereal floating eyes and ears, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Ammorbidire Terra spell, solid grey stone melting into a bubbling pool of soft brown mud and glowing earth magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Arco di Bronwyn spell, a fierce concentrated blast of compressed air shaped like a rippling invisible shockwave, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Arrugginire spell, corrosive reddish-brown magic rapidly oxidizing and crumbling a pile of metallic weapons, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Bastione di Elgan spell, a sturdy glowing wall of reinforced heavy stone blocks held together by pulsing earth magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Camera di Dormyn spell, a translucent soundproof dome of faint silver magic isolating the space inside, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Compromettere Focus spell, chaotic red and purple sparks disrupting and shattering a glowing magical staff crystal, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Corrente spell, a rapid powerful stream of swirling deep blue water forcefully rushing in a single direction, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Cryfhau spell, heavy earth magic coating phantom muscles with a durable layer of glowing cracked stone, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Essenza della Pozione spell, a perfectly spherical floating droplet of pure water transforming into a glowing green alchemical liquid, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Estrazione di Ainfra spell, glowing magical tendrils extracting toxic green venom out of a dark pool of blood, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Fiamma Innocua spell, a warm brightly glowing golden fire illuminating the darkness without burning its surroundings, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Forgia del Mago spell, an ethereal magical anvil radiating glowing orange heat and swirling smithing embers, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Frana di Bekker spell, a violent cascading landslide of heavy jagged boulders and earth crashing downward, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Fulmine Globulare spell, a highly unstable hovering sphere of crackling blue and white lightning, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Fumo di Vahila spell, a dense choking cloud of thick black smoke and grey volcanic ash completely obscuring the area, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Fuoco Vivente spell, a roaring campfire magically animating into the shape of a fiercely burning ethereal hound, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    55: [
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Getto d'Acqua spell, a highly pressurized piercing stream of deep blue elemental water blasting forward, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Gwyntog spell, a violent chaotic gale of slashing white wind currents and debris, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Immobilizzare Lingua spell, a glowing restrictive band of magical force clamping tightly shut over a phantom mouth, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Individuare Linee Geomantiche spell, glowing intricate veins of pulsing blue and green magical ley lines revealing themselves across the earth, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Intensificare Odore spell, swirling colorful luminous vapors tracing an invisible scent trail through the air, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Invaerne spell, a terrible swirling blizzard of pale blue frost, jagged ice, and heavy snow, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Laccio Spettrale spell, a ghostly pale green ethereal noose pulling tight around an invisible ankle, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Macchia spell, a spreading corruptive blotch of deep unnatural ink-like shadows seeping into the stone, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Mano della Tempesta spell, a hovering phantom hand crackling with violent miniature thunderclouds and arcing blue lightning, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Manto spell, a shimmering highly realistic optical illusion blending seamlessly into the surrounding dark stone like a chameleon, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Metodo di Savolla spell, a brutal defensive barricade of sharpened rocks and jagged earth spikes erupting upwards, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Modellare Terra spell, swirling earth magic effortlessly molding solid grey granite as if it were soft pliable clay, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Morte di Fergus spell, a lethal concentrated explosion of blinding white-hot fire and expanding shockwaves, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Nastro Invisibile spell, a faint nearly imperceptible magical tripwire glowing with a deadly translucent shimmer, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Piedi Leggeri spell, swirling gentle updrafts of pale wind magic cushioning invisible footsteps, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Piena di Ys spell, a devastating massive tidal wave of crushing dark blue ocean water, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Pilastro di Terra spell, a towering solid column of heavy bedrock shooting violently upward from the ground, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Portale Trappola spell, a deceptive chaotic vortex of swirling purple space-time magic cleverly disguised on the floor, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Porta di Cenere spell, swirling glowing embers and grey ash opening a momentary mystical passageway, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Rafforzare spell, earth magic infusing a steel shield and granting it a glowing impenetrable diamond-like sheen, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    56: [
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Ragnatela di Ghiaccio spell, a sticky expanding snare of razor-sharp flash-frozen pale blue frost and icicles, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Recupero Alchemico spell, swirling arcane energy extracting distinct glowing colored powders and herbs from a spilled potion, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Respiro di Aurora spell, mesmerizing undulating ribbons of green pink and violet ethereal lights soothing the air, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Riaprire Portale spell, a crackling jagged tear in reality being forced open by glowing blue dimensional magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Rubare Incantesimo spell, grasping greedy ethereal phantom hands snatching glowing red magic away from its source, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Schermo Magico spell, a solid shimmering disc of protective blue arcane energy violently deflecting a phantom arrow, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Sciame di Javed spell, a terrifying cloud of buzzing aggressive fiery magical insects composed of living sparks, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Soffio di Fuoco spell, a devastating roaring cone of crimson flames erupting from a phantom mouth, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Specchio Oscuro di Bekker spell, a hovering sinister black glass mirror reflecting a twisted pain-inducing shadow, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Stasi Cristallina spell, a solid flawless block of glowing amber crystal encasing a trapped phantom figure, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Tocco del Fabbro spell, glowing intense magical heat repairing the shattered blade of a steel sword with mystical sparks, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Tocco Fulminante spell, lethal erratic arcs of bright blue lightning jumping aggressively from phantom fingertips, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Vampata del Korath spell, a scorching suffocating wave of intense desert heat, cracked earth, and shimmering mirages, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Velo di Fuoco spell, a swirling protective aura of dancing orange flames wrapping around an unseen figure, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Velo di Polvere spell, a dense blinding cloud of swirling abrasive sand and heavy brown dust, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Maledizione della Pestilenza curse, a sickening toxic green aura accompanied by scurrying spectral rats and swarming plague insects, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Maledizione del Vagabondo curse, heavy ethereal chains of glowing dark chaotic magic binding bleeding wandering phantom feet, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Maledizione Mostruosa curse, violent dark purple and black magic painfully twisting and mutating an ethereal human silhouette into a beast, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Persecuzione curse, creepy elongated shadowy figures with glowing yellow eyes constantly stalking an unseen victim, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Bisogno Insaziabile curse, a terrifying withered spectral maw drooling with cursed green energy radiating an aura of eternal starvation, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    57: [
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Fattura della Dimenticanza hex, a thick grey magical fog wrapping around an ethereal brain and obscuring its glowing memories, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Fattura Odiosa hex, swirling aggressive crimson magic inciting uncontrollable anger around an unseen target, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Maledizione della Temperanza curse, heavy ethereal chains of glowing purple magic completely sealing a phantom goblet of wine, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Malocchio hex, a glaring toxic green ethereal eye imposing sudden misfortune and radiating cursed energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Ossa di Vetro hex, a translucent glowing skeletal arm revealing painfully fragile and cracking internal bones, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Il Bacio della Pesta hex, a phantom rotting female face blowing a sickly green and black cloud of disease and pestilence, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Il Prurito Perenne hex, a swarm of crawling magical insects made of biting red light burrowing into phantom skin, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the La Fattura della Bestia hex, savage phantom wolf claws and a bestial dark shadow looming over a cursed soul, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the La Fattura delle Ombre hex, suffocating black tendrils of animated darkness actively binding an invisible victim, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the La Fortuna del Diavolo hex, cursed burning gold coins and chaotic dark red magic manipulating fate, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the L'Incubo hex, terrifying shadowy demonic figures emerging from a dense suffocating violet mist, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Restaurare Cadavere necromancer spell, glowing green and black magic seamlessly knitting together torn dead flesh and restoring decay, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Tempesta di Anime necromancer spell, a howling violent vortex of tortured pale green spectral faces and swirling ectoplasm, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Spiriti Senza Pace Expert necromancy rules, depicting intricate ink illustrations of vengeful intermediate spirits and protective wards, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Spiriti Senza Pace Master necromancy rules, depicting terrifying ink illustrations of high-level wraiths, demons, and forbidden dark rituals, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Spiriti Senza Pace Novice necromancy rules, depicting basic ink illustrations of restless spirits and the initial dangers of goetia, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Creare Faro dell'Anima necromancer ritual, a sinister totem constructed from bone and ash radiating a pulsating pale blue spectral light attracting the dead, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Rianimare Cadavere necromancer ritual, dark violet necrotic energy breathing false unnatural life into a shattered skeleton, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Sintesi di Cadfan necromancer ritual, a horrifying amalgamation of severed limbs and stitched corpses bound together by glowing purple necrotic lightning, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Sogno Blu di Hanmarvyn necromancer ritual, swirling deep blue necrotic mist entering a dead skull to reveal the faded golden memories of a deceased mind, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    58: [
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Somne witcher sign, a hypnotic swirling mist of soothing pale violet sleep magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Supirre witcher sign, glowing ethereal silver sonic waves rippling outward to capture and amplify distant whispers and sounds, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Kingdom of Aedirn, depicting contested borders and rolling plains with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Kingdom of Cintra, depicting the capital city and the Yaruga river borders with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Dol Blathanna, depicting the lush elven Valley of Flowers and ancient forests with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Kingdom of Kaedwen, depicting massive dense forests, snowy northern peaks, and rugged terrain with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Kovir and Poviss, depicting the wealthy northern snowy realms and trade ports with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of The Far North, depicting uncharted freezing wastelands, icy tundras, and jagged mountains with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Mahakam, depicting the rugged snowy mountain peaks, dwarven strongholds, and deep mines with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Ofier, depicting distant exotic lands, vast deserts, and rich trade routes with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Kingdom of Redania, depicting the powerful wealthy realm, rich farmlands, and the city of Tretogor with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Kingdom of Temeria, depicting the central realm, the Pontar river, and the capital Vizima with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Mystical Analysis, featuring a glowing magical lens revealing hidden glowing arcane dust and runes scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Analyze Evidence, featuring sharp metal tweezers, a measuring tape, and a torn blood-stained piece of cloth scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Decipher, featuring a cryptic coded parchment covered in strange symbols next to an open inkwell and a quill scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Examine Corpse, featuring polished steel surgical tools and a detailed sketch of a monster's internal anatomy scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Examine Scene, featuring a rapidly sketched map of a crime scene dotted with tiny wooden markers and charcoal scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Interrogation, featuring a shiny silver coin, a threatening rusted dagger, and a written confession letter scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Tailing, featuring a sketched map of city alleyways marked with a shadowed footprint symbol and a compass scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Gossip, featuring anonymously written letters, a spilled cup of tavern ale, and scattered playing cards lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    59: [
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Research, featuring a pile of heavy dusty archaic tomes, open scrolls, and a pair of spectacles scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Follow the Money, featuring a trail of shiny gold Nilfgaardian florens resting next to an open merchant's accounting ledger on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation clue Follow Tracks, featuring a massive beast's muddy footprint preserved in wax next to a brass magnifying lens scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Authority, featuring a heavy official document completely blocked by a massive red wax seal bearing a royal crest, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Weather, featuring vital investigation notes completely soaked by rain, ruined by mud, and partially frozen with pale blue frost, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Conspiracy, featuring a tangled chaotic web of red string connecting various mysterious names and torn portraits, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Distraction, featuring a chaotic mess of unrelated papers, broken bottles, and scattered mixed coins obscuring the truth, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Exhaustion, featuring a completely burned-down candle, a spilled inkwell, and a cracked hourglass indicating severe fatigue, scattered on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle False Trail, featuring a misleading torn map leading to a crossed-out dead end aggressively marked with red ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Missing Clue, featuring a complex intricate wooden puzzle board missing a single crucial central piece, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Passage of Time, featuring an old dusty glass hourglass with all the sand completely drained to the bottom indicating time has run out, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Hostile Environment, featuring detective notes severely stained with toxic green swamp slime, moss, and creeping vines, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Gossip, featuring multiple conflicting forged letters full of crossed-out lies and deceitful whispers, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, representing the investigation obstacle Unfamiliar Situation, featuring a bizarre alien magical artifact of unknown origin resting confusingly on a completely blank parchment, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the rules of Mystery Complexity, depicting branching paths and logical investigation webs with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the rules of Investigation Focus, depicting intricate mind-mapping and concentration techniques with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed architectural floor plan of The Singing Sword tavern, depicting tables, hearths, and rooms with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling Tavern Quirks, featuring amusing ink illustrations of brawls, bards, and strange patrons, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a vast detailed parchment map outlining Roads and Distances of the Continent, depicting major trade highways and travel times with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment detailing Types of Venues and Taverns, featuring ink illustrations of high-class inns and shady dive bars, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    60: [
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Accademia di Ban Ard, featuring ink illustrations of rowdy male magic students practicing martial combat and spells in a stone courtyard, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Accademia di Oxenfurt, featuring detailed ink diagrams of scientific inventions, books, and the bustling university city, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling La Vita di un Witcher, featuring grim anatomical sketches of monsters, a bloody silver sword, and notes on survival, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Cacciatori di Maghi, featuring dramatic ink illustrations of burning pyres, shackled mages, and stern zealots, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Chiesa di Kreve, featuring illustrations of grand temples, holy symbols, and priests commanding divine lightning, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Confraternita dei Maghi, featuring ink illustrations of an assembly of powerful sorcerers gathered around a glowing magical orb, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling Druidismo, featuring beautiful ink illustrations of ancient sacred oak trees, standing stones, and druidic circles, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling L'Epoca d'Oro dei Witcher, featuring heroic historical ink illustrations of the six united witcher schools fighting massive legendary beasts, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the goddess Freya, featuring Skellige runes and illustrations of a pregnant goddess accompanied by a falcon and a cat, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Fuoco Eterno, featuring ink illustrations of zealous priests in red and white robes worshipping a massive blazing flame, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Havekar, featuring shady woodland smugglers trading illegal goods and weapons with elven rebels, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling Il Grande Sole, featuring the imposing golden sun emblem of the Nilfgaardian Empire and bowing devout subjects, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Isola di Thanedd, depicting the magical academy of Aretuza, Garstang, and the towering Tor Lara with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Kaer Morhen, depicting the ruined Wolf School mountain fortress and its defensive walls with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Loggia delle Maghe, featuring a shadowy secret round table of powerful female sorceresses plotting in the dark, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Luna Crescente, featuring subtle ink illustrations of an enigmatic secret society, spies, and a glowing crescent moon, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling Luoghi di Potere, featuring ink illustrations of ancient runestones radiating raw magical elemental aura, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the goddess Melitele, featuring ink illustrations of the three statues representing the Young, the Mother, and the Crone with offerings of fruits, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the dark goddess Niya (Lilit), featuring a sinister ink illustration of a multi-armed deity demanding blood offerings, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Ordine della Rosa Fiammeggiante, featuring a proud armored knight holding a shield with a burning rose emblem, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    61: [
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling San Gregory, featuring ink illustrations of the holy man distributing bread and gold to the starving people of Novigrad, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Scoia'tael, featuring ink illustrations of fierce elven archers wearing woodland camouflage and squirrel tails, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Scuola della Manticora, featuring an eastern wandering witcher holding a curved saber and a manticore medallion, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Scuola della Vipera, featuring a deadly assassin witcher wielding dual poisoned short blades and a viper medallion, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Scuola dell'Orso, featuring a massive mountain witcher clad in heavy steel armor with a bear medallion, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Scuola del Gatto, featuring a ruthless agile witcher assassin from the Dyn Marw caravan wearing a cat medallion, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Scuola del Grifone, featuring an honorable witcher channeling intense magic against multiple foes with a griffin medallion, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Scuola del Lupo, featuring a traditional scarred witcher carrying two swords on his back with a wolf medallion, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Scuola di Aretuza, featuring rigorous and elegant female sorceresses studying complex magical theory, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Valle del Pontar, depicting the vital trade river, contested borders, and bustling ports with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the ancient god Veyopatis, featuring a savage wooden idol with an open maw surrounded by dark forest offerings, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling Demoni Maggiori e Veri Nomi, featuring a horrifying ink sketch of a powerful goetic demon surrounded by glowing true names, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment defining Linee Geomantiche, depicting a vast map of the continent crossed by glowing intersecting veins of raw magical power, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment detailing Water Ley Lines, depicting flowing blue magical currents tracing the paths of great rivers and oceans, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment detailing Air Ley Lines, depicting swirling white magical currents tracing the high mountain peaks and atmospheric winds, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment detailing Fire Ley Lines, depicting blazing red magical currents intersecting dangerously over volcanoes and geothermal vents, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment detailing Earth Ley Lines, depicting solid green and brown magical currents pulsing deep within bedrock and ancient forests, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment detailing Priests and Druids drawing from Ley Lines, featuring holy figures kneeling and safely absorbing earth magic, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment detailing the act of Drawing Power, featuring a mage absorbing an overwhelming surge of chaotic elemental energy from a ley line, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment detailing Places of Power, featuring a detailed ink sketch of an ancient monolith crackling with concentrated magical resonance, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    62: [
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment depicting the drafting of the Tome of Chaos, featuring the scholars Brandon of Oxenfurt and Glynnis var Treharne writing amidst piles of magical books, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the History of Druids, featuring ink illustrations of the first ancient druids planting sacred seeds in the primeval forests, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Life of a Mage, featuring an opulent sorcerer in a lavish royal court manipulating political strings, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the School Life of Mages, featuring young apprentices in robes practicing levitation and basic spells in a grand library, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment featuring a Skellige Dialect Glossary, translating harsh northern runes next to a sketch of a mighty wooden drakkar, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the Society of Mages of the High Mountain, featuring isolated sorcerers meditating on a freezing snowy peak, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting, character portrait of a Smuggler, a shady and resourceful rogue with a sly grin, wearing a dark cloak and standing next to hidden crates of illegal untaxed goods, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting, character portrait of a Courier, a fast and reliable traveler wearing light leather riding gear, holding a heavily sealed important satchel with a determined expression, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting, character portrait of a Scout, a vigilant woodland ranger wearing green and brown camouflage, holding a drawn hunting bow and scanning the horizon, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting, character portrait of a Peasant, a weary and dirt-smudged villager wearing coarse woven clothes, holding a worn wooden pitchfork, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a medical parchment detailing Complex Crits, featuring anatomical diagrams of severe bleeding wounds, fractured ribs, and torn muscles with red ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a medical parchment detailing Difficult Crits, featuring gruesome anatomical diagrams of crushed organs, shattered jaws, and deep lacerations with red ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a medical parchment detailing Deadly Crits, featuring brutal anatomical diagrams of decapitations, severed hearts, and fatal strikes with heavy red ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, a medical parchment detailing Simple Crits, featuring minor anatomical diagrams of sprained ankles, shallow cuts, and bruised hands with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an investigative parchment detailing an Unarmed Fumble, featuring a sketch of a comical misstep during a tavern fistfight resulting in a self-inflicted injury, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an investigative parchment detailing a Ranged Fumble, featuring a sketch of a suddenly snapped bowstring whipping back and a dropped arrow, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an investigative parchment detailing a Melee Attack Fumble, featuring a sketch of an off-balance warrior clumsily dropping their steel sword during a swing, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an investigative parchment detailing a Melee Defense Fumble, featuring a sketch of a stumbling defender holding a completely shattered wooden shield, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an arcane parchment detailing the Effects of Elemental Disasters, featuring chaotic sketches of magic violently backfiring with uncontrolled fire and ice explosions, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
        "Digital painting viewed from directly above, top-down perspective, an arcane parchment detailing the Outcomes of Mage Magical Disasters, featuring a horrifying sketch of a sorcerer suffering severe physical feedback and bleeding from the eyes, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ],
    63: [
        "Digital painting viewed from directly above, top-down perspective, an arcane parchment detailing the Dangers of Necromancy, featuring a terrifying dark ink illustration of a foolish necromancer being violently dragged into the abyss by vengeful restless spirits, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
    ]
}

def escape_js(text):
    return text.replace("'", "\\'").replace('"', '\\"')

for batch_num, prompts in new_prompts_data.items():
    file_path = os.path.join(scratch_dir, f"prompts_batch_{batch_num}.html")
    if not os.path.exists(file_path):
        print(f"File non trovato: {file_path}")
        continue
    
    with open(file_path, 'r', encoding='utf-8') as f:
        html = f.read()
    
    # Trova tutti i blocchi .item usando una logica più robusta
    # Gli item finiscono solitamente prima del prossimo <div class="item"> o prima di </body
    items = re.findall(r'<div class="item">.*?</div>\s*(?=<div class="item"|</body>|<script)', html, re.DOTALL)
    
    if len(items) == 0:
        # Fallback se non trova il lookahead
        items = re.findall(r'<div class="item">.*?</div>', html, re.DOTALL)

    print(f"Batch {batch_num}: trovati {len(items)} item.")
    
    updated_html = html
    
    for i, new_prompt in enumerate(prompts):
        if i >= len(items):
            break
            
        old_item = items[i]
        
        # Sostituisci il contenuto del prompt-box
        # <div class="prompt-box" id="p-FILENAME">PROMPT</div>
        new_item = re.sub(r'(<div class="prompt-box"[^>]*>).*?(</div>)', f'\\1{new_prompt}\\2', old_item, flags=re.DOTALL)
        
        # Sostituisci il parametro di copyToClipboard
        # <button onclick="copyToClipboard('PROMPT', this)">
        # Cerchiamo di essere molto specifici per evitare match parziali
        new_item = re.sub(r"copyToClipboard\('.*?', this\)", f"copyToClipboard('{escape_js(new_prompt)}', this)", new_item, flags=re.DOTALL)
        
        updated_html = updated_html.replace(old_item, new_item)
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(updated_html)
    
    print(f"Batch {batch_num} aggiornato.")
