const fs = require('fs');

const prompts54 = [
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Druidic Bond invocation, glowing ethereal green vines connecting in a unified knot of nature magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Goat's Mantle invocation, a spectral aura of a horned goat woven from wild woodland magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Fear invocation, terrifying primal illusions of apex predators formed by dark green shadows, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Wolf's Pace invocation, swirling wind and phantom wolf paws granting supernatural speed, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Druidic Presence invocation, a majestic aura of ancient forest energy and falling golden leaves, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Scent of Flowers invocation, a swirling breeze carrying vibrant glowing petals and sweet pink magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Purify Water invocation, a crystal-clear sphere of cleansed water radiating gentle blue magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Druidic Refuge invocation, a protective dome of rapidly grown thick wooden roots and blooming vines, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Blood of the Earth invocation, glowing molten magma and raw geothermal energy seeping upward, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Scrying invocation, a perfectly still pool of enchanted water reflecting distant ethereal visions, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Track invocation, glowing ethereal footprints illuminated by pale green hunter's magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Druidic Senses invocation, a subtle aura of heightened perception with glowing amber woodland eyes, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Whispers invocation, twisting air currents carrying faint glowing runic messages on the wind, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Lightning Storm invocation, miniature dark storm clouds crackling with violent blue electricity, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Earth invocation, heavy chunks of soil and bedrock levitating in a swirl of dense brown magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Root Trap invocation, violent grasping thorny roots bursting upwards in a snare, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Thunder invocation, a violent rippling sonic shockwave of compressed air, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Fang of Mother Nature invocation, a massive razor-sharp spectral thorn dripping with primal venom, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a sinister Altar of Crows, carved from dark jagged stone, adorned with black feathers, melted candles, and dried bloodstains, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Animate the Dead spell, swirling purple necrotic energy lifting scattered skeletal remains, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts55 = [
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of a Circle of Protection, perfectly drawn chalk boundaries glowing with warding blue arcane runes, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Communion with the Dead ritual, eerie pale green ghost spirits rising from the shadows, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Manipulation of the Deceased spell, sinister crimson arcane strings puppeteering bone and flesh, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Eyes of the Evil Eye spell, multiple hovering spectral eyes glaring with cursed yellow light, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Word of Death spell, a devastating sonic shockwave of black necrotic energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Blood Bullet spell, a condensed hovering projectile formed from boiling cursed crimson blood, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of Spectral Reanimation, a howling wraith forming from swirling grey and black mists, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Spirit Binding Ritual, heavy ethereal chains of glowing purple magic restraining a struggling phantom, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of Corrupted Blood, bubbling toxic green and black blood seeping with disease, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Path of the Graveyard, creeping heavy graveyard fog obscuring cracked tombstones and dead grass, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Whisper of Skulls, floating bleached skulls emitting pale blue flames from their eye sockets, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Touch of the Grave, a skeletal phantom hand radiating freezing pale blue necrotic frost, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Banshee's Wail, a terrifying sonic distortion of shrieking pale spectral energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the See Death spell, a chilling aura of black premonitions and phantom skulls, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Evil Eye hex, a glaring toxic green ethereal eye imposing sudden misfortune, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Spalla Plateau, depicting elevated highlands and rough terrain with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Skellige Archipelago, depicting rugged islands and rough seas with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Yaruga Bay, depicting the wide river mouth and coastal shores with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Lower Aedirn, depicting contested borders and rolling plains with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Lower Posada, depicting a rustic valley settlement with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts56 = [
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the town of Belhaven, depicting streets and local landmarks with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the town of Blaviken, depicting the coastal port and market squares with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the battlefield of Brenna, depicting strategic hills and troop positions with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Brokilon Forest, depicting dense ancient woodlands and dryad territories with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the kingdom of Brugge, depicting river borders and dense forests with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Caer Myrkvid, depicting the ancient druidic forest circle with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the fortress of Caer Troide, depicting the towering mountain keep in Skellige with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of a Deserted Castle, depicting ruined walls and abandoned courtyards with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Stygga Castle, depicting the sinister ruined mountaintop citadel with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the kingdom of Cidaris, depicting bustling coastlines and naval ports with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the kingdom of Cintra, depicting the capital city and the Yaruga border with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Dol Angra Valley, depicting the contested military border zone with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a weathered heraldic wooden round shield of Skellige Clan an Craite, featuring a painted roaring sea boar on a red and black background, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a weathered heraldic wooden round shield of Skellige Clan Brokvar, featuring painted traditional clan motifs on a dark blue background, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a weathered heraldic wooden round shield of Skellige Clan Drummond, featuring a painted bear motif on a purple background, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a weathered heraldic wooden round shield of Skellige Clan Heymaey, featuring a painted mythical sea beast on a green background, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a weathered heraldic wooden round shield of Skellige Clan Tordarroch, featuring a painted mountain peak on a grey background, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a weathered heraldic wooden round shield of Skellige Clan Tuirseach, featuring painted wild axes on a dark brown background, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an elegant heraldic banner of the Nilfgaardian Var Attre family, featuring intricate gold and black noble crests on fine velvet, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Riverdell County, depicting peaceful agricultural lands and rivers with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

function updateHtmlFile(filePath, newPrompts) {
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    return;
  }
  let content = fs.readFileSync(filePath, 'utf8');
  let promptIndex = 0;
  
  content = content.replace(/<div class="prompt-box"[^>]*>([\s\S]*?)<\/div>\s*<button onclick="copyToClipboard\('(.*?)', this\)">Copia Prompt<\/button>/g, (match, oldDivContent, oldBtnContent) => {
    if (promptIndex < newPrompts.length) {
      const newPrompt = newPrompts[promptIndex];
      const escapedPrompt = newPrompt.replace(/'/g, "\\'");
      const newMatch = match
        .replace(oldDivContent, newPrompt)
        .replace(oldBtnContent, escapedPrompt);
      promptIndex++;
      return newMatch;
    }
    return match;
  });
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

updateHtmlFile('scratch/prompts_batch_54.html', prompts54);
updateHtmlFile('scratch/prompts_batch_55.html', prompts55);
updateHtmlFile('scratch/prompts_batch_56.html', prompts56);
