const fs = require('fs');

const prompts42 = [
  "Digital painting, character portrait of Voren of Dillingen, an old and battle-hardened veteran Witcher, scarred face and a complex prosthetic limb replacing a devastating wound from a fight with a Fiend, wearing weathered Witcher armor, fierce and resilient expression, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of Zoltan Chivay, a robust and cheerful Mahakaman dwarven veteran, iconic mohawk hair and thick beard, wearing practical leather and mail armor, holding a heavy dwarven battle axe, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a sleek Cat School witcher silver sword, elegant lightweight crossguard featuring subtle feline motifs, gleaming silver blade infused with faint red ruby dust magic, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an agile Cat School witcher crossbow, precision design crafted from black steel and beast bones, intricate leather wrappings, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a regal Griffin School witcher silver sword, brass and gold-adorned crossguard with griffin motifs, pristine silver blade radiating a subtle ethereal glow of quintessence magic, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a robust Griffin School witcher crossbow, heavy dark iron frame with brass griffin engravings, tension strings made of dark organic archespore tentacles, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an elegant Vrihedd Cavalry Sword, featuring a sleek subtly curved elven blade forged from distinct blue-tinted steel, ornate leather-wrapped hilt, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the legendary Moon Blade silver relic sword, exquisite ancient craftsmanship with a silver blade that subtly glows with pale ethereal lunar magic, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a mastercrafted Meteoric Sword, featuring a dark meteoric steel blade reflecting a subtle iridescent oil-like sheen of multicolored elemental magic, sturdy ornate hilt, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Harpy's Spur throwing knife, perfectly balanced straight double-edged blade forged from dark steel, dripping with highly toxic green venom, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, Thorn, a legendary relic sword, featuring a menacing dark steel blade with wicked serrated edges resembling jagged briars, sinister ornate hilt, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an exquisite Elven Zefhar longbow, beautifully curved frame made of dark flexible wood reinforced with ancient elven magic, taut glowing bowstring, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a heavy Hunting Crossbow, robust practical design carved from thick dark wood, reinforced with iron plating and a powerful draw mechanism, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a deadly Viroledan Blade, featuring a dark perfectly balanced steel blade dripping with subtle green toxic venom and an elegant hilt, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a sturdy War Spear, featuring a long battle-worn hardened wooden shaft topped with a broad razor-sharp dark iron spearhead, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a heavy Blunt Spear used for training and tourneys, featuring a long sturdy wooden shaft topped with a rounded unsharpened iron tip, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a crude but devastating Peasant's Mallet, featuring a massive heavy wooden head reinforced with thick iron bands and wax, sturdy wooden handle, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a brutal Knight's Warhammer, featuring a heavy black steel hammer head with a wicked piercing spike, leather-wrapped hardened wood handle, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a menacing Partisan polearm, featuring a broad black steel spearhead with sharp lateral parrying blades, mounted on a sturdy hardened wooden shaft, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a flawlessly crafted Ducal Sword, elegant and deadly black steel blade paired with a rich gold-adorned ornate hilt and crossguard, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

function updateHtmlFile(filePath, newPrompts) {
  let content = require('fs').readFileSync(filePath, 'utf8');
  let promptIndex = 0;
  
  content = content.replace(/<div class="prompt-box"[^>]*>([\s\S]*?)<\/div>\s*<button onclick="copyToClipboard\('(.*?)', this\)">Copia Prompt<\/button>/g, (match, oldDivContent, oldBtnContent) => {
    if (promptIndex < newPrompts.length) {
      const newPrompt = newPrompts[promptIndex];
      const escapedPrompt = newPrompt.replace(/'/g, "\\'");
      const newMatch = match
        .replace(oldDivContent, newPrompt)
        .replace(oldBtnContent, escapedPrompt);
      promptIndex++;
      return newMatch;
    }
    promptIndex++;
    return match;
  });
  
  require('fs').writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

updateHtmlFile('scratch/prompts_batch_42.html', prompts42);
