const fs = require('fs');

const prompts43 = [
  "Digital painting viewed from directly above, top-down perspective, a luxurious Quality Inn Room, featuring polished rich wooden floors, a lavish four-poster bed with fine velvet covers, a crackling warm hearth, and an elegant wooden table with a feast, perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an Enchanted Amulet, featuring a beautiful silver chain and a glowing magical gemstone pulsing with ethereal arcane energy, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Magical Elven Rope, finely woven from shimmering pale threads that subtly glow with ethereal light and ancient sylvan magic, coiled neatly, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Magic Formula scroll, an ancient parchment covered in glowing arcane runes and esoteric alchemical diagrams written in shimmering ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a traditional wooden Sailboat, featuring a sturdy curved hull and a furled white canvas sail attached to a central mast, floating on dark rippling water, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a set of Leather Barding for a horse, crafted from thick hardened dark leather with reinforced stitching and sturdy iron buckles, arranged flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a set of Iron Chainmail Barding for a warhorse, featuring heavy interlocking dark iron rings and thick leather padding, arranged flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, sturdy Military Saddlebags, crafted from heavy reinforced dark leather with thick iron buckles and external cargo straps, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an elegant horse-drawn Carriage, featuring a polished dark wood cabin with gilded details, velvet-curtained windows, and sturdy reinforced wheels, resting on a muddy cobblestone road, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a sturdy Cutter boat, featuring a sleek weathered wooden hull designed for speed and fishing, with tightly wound rigging and a lowered mast, floating on dark rippling water, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a massive Sailing Ship, featuring a heavy reinforced dark wooden hull, multiple thick masts with furled sails, and a detailed wooden deck with cargo hatches, floating on dark rippling ocean water, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a pair of practical horse Blinders, crafted from worn dark leather with thick stitching and sturdy iron clasps to keep a mount calm, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a pair of sleek Racing Blinders for a horse, crafted from fine lightweight dark leather with aerodynamic styling and polished silver buckles, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a heavy Cavalry Saddle, crafted from thick padded dark leather, featuring high pommels, sturdy iron stirrups, and a built-in weapon scabbard, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a sleek Racing Saddle, minimalist and lightweight design crafted from fine supple dark leather with polished silver stirrups, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a spy's Amplifier, a small cleverly designed brass and iron listening horn used to eavesdrop through doors, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Ring of Favor, an exquisite gold ring adorned with a gleaming precious gemstone and intricate noble engravings, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the mastercrafted Manticore School witcher armor, featuring reinforced dark leather, practical alchemical bandoliers, and faint magical runes, arranged flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the mastercrafted Bear School witcher armor, a heavy and brutal set featuring thick dark iron plates, heavy chainmail, and a thick fur mantle, arranged flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the mastercrafted Viper School witcher armor, a sleek and agile set featuring dark scaled leather, subtle poison-green accents, and twin snake motifs, arranged flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts44 = [
  "Digital painting viewed from directly above, top-down perspective, heavy Reinforced Axles for a wagon, forged from thick blackened iron and sturdy Mahakaman oak, showing signs of heavy-duty craftsmanship, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a heavy Bear School witcher crossbow, brutal robust design crafted from dark wood and reinforced with dark iron and beast bones, thick siren-chord bowstring, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a sinister Black Magic Doll, crudely fashioned from woven roots, dark stained cloth, and human hair, pierced with rusted iron pins and exuding a faint crimson cursed aura, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Hidden Trunk, a clever wooden chest designed to be concealed inside larger furniture, featuring subtle invisible seams and a flush lid, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a small worn leather pouch tipped over, spilling a cluster of perfectly round glass and iron marbles, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of Broderick the Beefsteak, a massive and incredibly muscular human brawler, bare-chested with thick scars and tavern tattoos, short cropped hair, heavy thick fists wrapped in bloody leather straps, tough and imposing expression, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a classic brass and glass compass, featuring an intricately engraved compass rose and a sharp magnetic needle pointing north, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an alchemical Distillation Chamber, a complex apparatus of heavy glass flasks, copper tubing, and a small iron heating brazier filled with glowing coals, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a thick glowing puddle of highly toxic monster Mucus, viscous green and yellow slime bubbling with corrosive acid and foul fumes, splattered flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Basic Wagon, a simple but sturdy wooden cart with four heavy spoked wheels and a flat open wooden cargo bed, resting on a muddy cobblestone road, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a robust Support Wagon, featuring a covered canvas top stretched over wooden hoops, loaded with visible barrels, crates, and travel gear, resting on a muddy cobblestone road, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a heavily armored War Wagon, featuring thick dark iron plating over solid oak, narrow arrow slits, and menacing reinforced spiked wheels, resting on a muddy cobblestone road, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a finely crafted Quality Wagon, featuring smooth varnished dark wood, polished brass fittings, and excellent suspension leaf springs, resting on a muddy cobblestone road, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a set of heavy-duty Cargo Straps, crafted from thick woven hemp and reinforced leather with heavy iron tightening ratchets, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a wooden board with a sliding false bottom revealing a Secret Compartment, hiding a few loose gold coins and a folded parchment, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a pair of heavy wooden wagon Props, thick sturdy oak beams with iron-capped ends used to stabilize a parked carriage, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a rustic Signal Horn, crafted from a large hollowed beast horn, polished and fitted with a brass mouthpiece and a leather carrying strap, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a high-quality Dwarven Whetstone, a perfectly rectangular block of fine dark Mahakaman sharpening stone engraved with a single dwarven rune, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of Elias von Drexel, a wealthy and calculating Northern nobleman, wearing an opulent velvet doublet with gold embroidery and a high ruffled collar, sharp features with a neatly trimmed goatee, shrewd calculating gaze, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a small metallic Signal Whistle, crafted from polished silver and hung on a simple leather cord, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

function updateHtmlFile(filePath, newPrompts) {
  let content = fs.readFileSync(filePath, 'utf8');
  let promptIndex = 0;
  
  content = content.replace(/<div class="prompt-box"[^>]*>([\s\S]*?)<\/div>\s*<button onclick="copyToClipboard\('(.*?)', this\)">Copia Prompt<\/button>/g, (match, oldDivContent, oldBtnContent) => {
    if (promptIndex < newPrompts.length) {
      const newPrompt = newPrompts[promptIndex];
      const escapedPrompt = newPrompt.replace(/'/g, "\\'");
      const newMatch = match
        .replace(oldDivContent, newPrompt)
        .replace(oldBtnContent, escapedPrompt);
      promptIndex++;
      return newMatch;
    }
    promptIndex++;
    return match;
  });
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

updateHtmlFile('scratch/prompts_batch_43.html', prompts43);
updateHtmlFile('scratch/prompts_batch_44.html', prompts44);
