const fs = require('fs');

const prompts48 = [
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Mark of Withering invocation, a sinister glowing curse symbol that prevents healing radiating dark ethereal energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Miracle of Lebioda invocation, a radiant burst of pure holy light bringing miraculous healing, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Shadow of Bleobheris, a massive protective canopy of ethereal ancient tree branches and deep green shadows, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Summoning Word, a glowing runic echo resonating through the air surrounded by ethereal animal spirits, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Quill of the Divine invocation, a glowing ethereal feather writing glowing memories in the air, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Well of Knowledge, a swirling pool of glowing blue magical water revealing ancient secrets, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of Omens of Doom, swirling dark clouds and ethereal ravens casting sinister shadowy curses, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Presence of the Divine, an overwhelming aura of brilliant golden holy light and majestic power, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of a Web of Roots, thick magical roots bursting from the ground in a tangled glowing green trap, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of Sagitta Aurea, a blazing golden arrow made of pure holy energy ready to strike, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Blood of the Berserker invocation, a savage crimson aura of boiling blood and primal rage, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Blood of the Mountain, glowing molten magma and intense geothermal energy seeping from the earth, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Sanctuary of the Black Wood, an impenetrable magical thicket of dark thorny vines and ancient wood, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Seal of Abundance, a glowing earth rune surrounded by rapidly blooming crops and golden wheat, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Seal of the Hunt, an ethereal glowing tracker's mark pulsing with predatory green magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of a Druidic Totem, a floating ethereal carving of animal spirits radiating powerful woodland magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Raven's Revenge invocation, a vicious swarm of spectral red-eyed ravens swirling in dark magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Winds of the Taiga, a freezing vortex of howling winds, snow, and pale blue winter magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Voice of the Advisor, a gentle glowing breeze carrying ethereal whispers of ancient wisdom, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of a Magic Barrier, a shimmering translucent dome of protective blue arcane energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts49 = [
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Artifact Compression, swirling violet arcane energy shrinking a struggling figure into a tiny jade statuette, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of a Consecration ritual, a perfectly drawn circle of holy salt glowing with radiant purifying golden light, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Construct Golem ritual, swirling earth magic animating a massive heart of stone and clay, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Hydromancy, a scrying pool of enchanted silver water displaying swirling ethereal visions, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of an Interactive Illusion, a hyper-realistic shifting mirage of light and shadow seamlessly bending reality, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of a Magic Message, a folded paper bird glowing with arcane runes flying on ethereal winds, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Oneiromancy, swirling hypnotic dream-mists of pale violet and silver revealing prophetic visions, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Pyromancy, a ritual brazier filled with dancing prophetic flames revealing shapes in the fire, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Ritual of Magic, a complex geometric array of chalk and candles glowing with raw chaotic energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Ritual of Life, an intricate mandala of blooming flowers and intense emerald healing magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of a Purification Ritual, cleansing white fire burning away dark magical corruption and foul curses, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of a Seance, a glowing Ouija circle surrounded by dancing candle flames and eerie pale green ghost spirits, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Telecommunication, a glowing xenovox mirror device projecting a shimmering arcane hologram, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a magical Spell Vase, a sealed clay jar inscribed with intricate arcane runes containing a swirling vortex of trapped spell energy, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Animate Armor ritual, ethereal blue arcane strings attaching to empty plates of steel like a puppet, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Wagerer's Pendant, a dark magical amulet crafted from aconite, bone, and a shard of engraved glass bound by leather, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of creating a Place of Power, raw elemental magic erupting from a carved stone monolith in a blinding pillar of light, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of creating a Crystal Skull, swirling arcane chisels carving an ethereal skull out of pure glowing quartz, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Beacon of the Unnatural ritual, a sinister pulsing signal of dark green energy attracting monsters, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Enchanting an Amulet, fine silver tools inscribing glowing blue arcane runes into a polished gemstone, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts50 = [
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Infusing a Trophy, an alchemical array transferring swirling magical energy into a preserved monster's head, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Mist of the Past ritual, pale glowing fog recreating ghostly silhouettes of historical events, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of a Magical Guest Register, an open ledger with enchanted ink writing names on its own, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Tyromancy, a bizarre scrying ritual involving aged cheese and swirling pungent yellow divination magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Chernobog Rune, a dark polished stone intricately engraved with a glowing purple dwarven rune that reflects damage, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Dazhbog Rune, a dark polished stone intricately engraved with a blazing fiery orange dwarven rune that inflicts burning, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Devana Rune, a dark polished stone intricately engraved with a deep crimson dwarven rune that causes severe bleeding, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Glyph of Water, a small polished stone engraved with a swirling deep blue arcane glyph radiating a cool ethereal aura, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Glyph of Air, a small polished stone engraved with a bright white arcane glyph surrounded by a subtle swirling breeze, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Glyph of Earth, a small polished stone engraved with a sturdy glowing green arcane glyph radiating heavy elemental magic, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Glyph of Fire, a small polished stone engraved with a fierce glowing red arcane glyph radiating intense heat, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Glyph of Magic, a small polished stone engraved with a vibrant violet arcane glyph pulsating with raw magical power, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Morana Rune, a dark polished stone intricately engraved with a toxic glowing green dwarven rune that inflicts poison, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Perun Rune, a dark polished stone intricately engraved with a crackling yellow dwarven rune that channels adrenaline, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Stribog Rune, a dark polished stone intricately engraved with a pale gray dwarven rune that causes staggering force, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Svarog Rune, a dark polished stone intricately engraved with a sharp glowing silver dwarven rune that pierces armor, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Triglav Rune, a dark polished stone intricately engraved with a heavy glowing bronze dwarven rune that stuns enemies, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Veles Rune, a dark polished stone intricately engraved with an ethereal glowing blue dwarven rune that focuses magic, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Zoria Rune, a dark polished stone intricately engraved with an icy pale blue dwarven rune that inflicts freezing, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Carys's Hail spell, a violent localized storm of razor-sharp jagged ice chunks and freezing winds, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

function updateHtmlFile(filePath, newPrompts) {
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    return;
  }
  let content = fs.readFileSync(filePath, 'utf8');
  let promptIndex = 0;
  
  content = content.replace(/<div class="prompt-box"[^>]*>([\s\S]*?)<\/div>\s*<button onclick="copyToClipboard\('(.*?)', this\)">Copia Prompt<\/button>/g, (match, oldDivContent, oldBtnContent) => {
    if (promptIndex < newPrompts.length) {
      const newPrompt = newPrompts[promptIndex];
      const escapedPrompt = newPrompt.replace(/'/g, "\\'");
      const newMatch = match
        .replace(oldDivContent, newPrompt)
        .replace(oldBtnContent, escapedPrompt);
      promptIndex++;
      return newMatch;
    }
    return match;
  });
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

updateHtmlFile('scratch/prompts_batch_48.html', prompts48);
updateHtmlFile('scratch/prompts_batch_49.html', prompts49);
updateHtmlFile('scratch/prompts_batch_50.html', prompts50);
