const fs = require('fs');

const prompts39 = [
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of Elven armor enhancements, featuring intricate ink blueprints of dark leather and beautifully engraved silver-steel plates alongside elvish notes, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a Halfling Protective Doublet, featuring detailed ink diagrams of hidden chainmail layers under a fabric coat with handwritten tailor's notes, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of Fiber armor enhancements, featuring ink illustrations of woven linen, double-threads, and cotton padding with alchemical measurements, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a Lyrian Leather Jacket, featuring ink blueprints of thick studded leather armor, precise measurements, and stitching patterns, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the forging of broadhead crossbow bolts, featuring precise ink diagrams of thick wooden shafts and wide razor-sharp iron tips, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the forging of bodkin crossbow bolts, featuring precise ink diagrams of armor-piercing hardened steel tips and fletching instructions, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of Dwarven armor enhancements, featuring heavy dwarven runes and ink blueprints of thick Mahakaman steel plates and chainmail rivets, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the forging of Orion throwing stars, featuring precise ink diagrams of heavy dark steel with jagged edges and aerodynamic calculations, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a Mahakaman Pavise heavy shield, featuring thick dwarven geometric blueprints for iron plating, hardened wood, and a ground-spike, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the creation of the True Binding Staff, featuring dark Goetia magic diagrams, demonic true names written in crimson ink, and twisted wood blueprints, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a Skellige Raider round shield, featuring ink diagrams of reinforced wood, iron rims, and notes on painting clan motifs, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of an Elven medium shield, featuring elegant sweeping ink diagrams of curved wood and steel leaf motifs, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the forging of a Vrihedd Cavalry Sword, featuring precise ink blueprints of a sleek curved elven blade and an ornate leather-wrapped hilt, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the forging of a Meteoric Sword, featuring intricate ink diagrams of a dark meteoric steel blade with alchemical notes on elemental magic tempering, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the crafting of an Elven Zefhar longbow, featuring elegant ink blueprints of a curved dark wood frame and magical string tension calculations, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a heavy Hunting Crossbow, featuring mechanical ink diagrams of a dark wood body, iron plating, and complex draw mechanisms, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the forging of a massive Flamberge two-handed sword, featuring detailed ink drawings of an intimidating wavy blade and heavy crossguard measurements, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the forging of a deadly Viroledan Blade, featuring ink blueprints of a perfectly balanced two-handed sword with specific notes on carving venom channels, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a War Spear, featuring ink diagrams of a broad razor-sharp iron spearhead mounted on a long hardened wooden shaft, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a Blunt Spear, featuring ink diagrams of a rounded unsharpened iron tip designed for tourneys and training, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

function updateHtmlFile(filePath, newPrompts) {
  let content = fs.readFileSync(filePath, 'utf8');
  let promptIndex = 0;
  
  content = content.replace(/<div class="prompt-box"[^>]*>([\s\S]*?)<\/div>\s*<button onclick="copyToClipboard\('(.*?)', this\)">Copia Prompt<\/button>/g, (match, oldDivContent, oldBtnContent) => {
    if (promptIndex < newPrompts.length) {
      const newPrompt = newPrompts[promptIndex];
      const escapedPrompt = newPrompt.replace(/'/g, "\\'");
      const newMatch = match
        .replace(oldDivContent, newPrompt)
        .replace(oldBtnContent, escapedPrompt);
      promptIndex++;
      return newMatch;
    }
    promptIndex++;
    return match;
  });
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

updateHtmlFile('scratch/prompts_batch_39.html', prompts39);
