const fs = require('fs');

const prompts57 = [
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Korath Desert, depicting vast barren sands, deadly dunes, and ancient ruins with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Dol Blathanna, depicting the lush elven Valley of Flowers and ancient forests with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Ellander, depicting the peaceful duchy and the great Temple of Melitele with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Etolia, depicting the southern Nilfgaardian province and its military routes with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Fen Carn, depicting the ancient and eerie elven cemetery with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Yaruga River, depicting its winding mighty course dividing the North and South with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Gemmera, depicting the harsh, martial Nilfgaardian province with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Gorthur Gvaed, depicting the hidden Viper School witcher fortress in the Tir Tochair mountains with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Gulet, depicting the bustling Northern city and its trade roads with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Haern Cadwch, depicting the snow-covered Bear School witcher keep in the Amell Mountains with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Hengfors, depicting the mountainous territories of the League of Hengfors with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Sedna Abyss, depicting the treacherous waters and magical anomalies of the island with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Kaer Morhen, depicting the ruined Wolf School witcher fortress in the Blue Mountains with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Kaer Seren, depicting the coastal Griffin School witcher fortress with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Kovir and Poviss, depicting the wealthy northern snowy realms with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Lyria and Rivia, depicting the twin realms and the river borders with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Maecht, depicting the Nilfgaardian province and its settlements with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Mag Deira, depicting the central Nilfgaardian province with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Mahakam, depicting the rugged snowy peaks and dwarven strongholds with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Maribor, depicting the heavily fortified Temerian city with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts58 = [
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Metinna, depicting the sprawling Nilfgaardian province and its vineyards with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Mount Carbon, depicting the towering dwarven peak with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Morgraig, depicting the ancient ruins with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Nazair, depicting the rebellious Nilfgaardian province with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Nilfgaard, depicting the vast Empire and the City of Golden Towers with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Novigrad, depicting the bustling Free City and its massive ports with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Pont Vanis, depicting the winter capital city in Kovir with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Redania, depicting the powerful Kingdom and its rich farmlands with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Stygga, depicting the sinister ruined mountaintop citadel with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Temeria, depicting the central Kingdom with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Toussaint, depicting the idyllic duchy, fairy-tale castles, and vineyards with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of the Pontar Valley, depicting the strategic and heavily contested river region with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Verden, depicting the coastal Kingdom and the edge of Brokilon forest with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Vicovaro, depicting the noble Nilfgaardian province with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Vizima, depicting the Temerian capital city built around its grand lake with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a detailed parchment map of Vyzima, depicting the royal palace and bustling trade routes of the capital with faded ink, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the 1250 Aretuza Revolt, featuring dramatic historical ink illustrations of rebellious mages and chaotic magic at the academy, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the 1263 Massacre of Cintra, featuring dramatic historical ink illustrations of burning city walls and the invading Nilfgaardian army, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient illuminated parchment chronicling the 1267 Thanedd Coup, featuring dramatic historical ink illustrations of dueling mages and the ruins of Garstang, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of an Academy Student, a young magical apprentice wearing formal Aretuza or Ban Ard school robes, holding a thick tome and looking ambitious, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts59 = [
  "Digital painting, character portrait of a Beguiler, a charismatic and elegant mage wearing alluring clothing with a sly smile, subtly manipulating a glowing pink magical charm, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of an Apprentice, a hardworking youth soot-stained from labor, wearing a rugged leather apron and holding basic tools, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of an Aristocrat, a wealthy noble wearing opulent velvet clothing with gold embroidery and a high ruffled collar, looking condescending, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Craftsman, sturdy and focused, wearing a heavy leather apron over a tunic, holding a smithing hammer and tongs, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of an Assassin, deadly and stealthy, face hidden beneath a dark hood, wearing sleek leather armor and holding a dripping poisoned dagger, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of an Athlete, muscular and bare-chested with scars and sweat, wearing sturdy trousers and leather wraps on their hands ready for a brawl, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Scoia'tael Activist, a fierce elven rebel wearing practical woodland camouflage and a squirrel tail, intense determined gaze, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of an Adventurer, rugged and travel-worn, wearing a heavy cloak over mixed armor, carrying a backpack, a sword, and a glowing lantern, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Bandit, rough and dangerous, wearing mismatched stolen armor and a grim bandana, holding a notched sword with a menacing grin, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Bard, flamboyant and charismatic, wearing a colorful feathered hat and a stylish doublet, holding a finely crafted lute with a dramatic pose, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Hunter, focused and lethal, wearing furs and dark leather, holding a sturdy hunting bow and accompanied by a loyal hound, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Bounty Hunter, ruthless and heavily armed, wearing reinforced armor and a wide-brimmed hat, holding a loaded crossbow and a wanted poster, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Knight, proud and heavily armored, wearing shining but battle-dented plate armor with a heraldic tabard, holding a heavy broadsword, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Charlatan, cunning and deceptive, wearing flashy but cheap clothing, holding a bottle of fake colorful snake-oil potion with a persuasive smile, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Merchant, wealthy and shrewd, wearing fine exotic silk robes, holding a leather-bound ledger and a heavy pouch of gold coins, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Peasant, resilient and weather-beaten, wearing simple coarse woven clothes, holding a wooden pitchfork and a woven basket of wheat, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Criminal, shady and secretive, hiding in the shadows of a dark alley, wearing a dark cloak and holding a stolen coin pouch, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Hardened Criminal, brutal and imposing, covered in prison tattoos and scars, wearing studded leather and wielding a heavy spiked club, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of an Herbalist, wise and practical, wearing earthy robes, carrying a woven basket full of rare glowing plants and medicinal roots, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting, character portrait of a Blacksmith, strong and powerful, muscles glistening with sweat from the forge heat, wearing iron-reinforced gauntlets and holding a glowing red-hot steel blade, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

function updateHtmlFile(filePath, newPrompts) {
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    return;
  }
  let content = fs.readFileSync(filePath, 'utf8');
  let promptIndex = 0;
  
  content = content.replace(/<div class="prompt-box"[^>]*>([\s\S]*?)<\/div>\s*<button onclick="copyToClipboard\('(.*?)', this\)">Copia Prompt<\/button>/g, (match, oldDivContent, oldBtnContent) => {
    if (promptIndex < newPrompts.length) {
      const newPrompt = newPrompts[promptIndex];
      const escapedPrompt = newPrompt.replace(/'/g, "\\'");
      const newMatch = match
        .replace(oldDivContent, newPrompt)
        .replace(oldBtnContent, escapedPrompt);
      promptIndex++;
      return newMatch;
    }
    return match;
  });
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

updateHtmlFile('scratch/prompts_batch_57.html', prompts57);
updateHtmlFile('scratch/prompts_batch_58.html', prompts58);
updateHtmlFile('scratch/prompts_batch_59.html', prompts59);
