const fs = require('fs');
const j = JSON.parse(fs.readFileSync('TheWitcherItaNewSystem/lang/it.json','utf8'));
const w = j.WITCHER;
console.log('WITCHER.Actor.Hp:', w.Actor.Hp);
console.log('WITCHER.Actor.Shield:', w.Actor.Shield);
console.log('WITCHER.Actor.Stamina:', w.Actor.Stamina);
console.log('WITCHER.Actor.Adrenaline:', w.Actor.Adrenaline);
console.log('WITCHER.Actor.tabs:', JSON.stringify(w.Actor.tabs));
console.log('WITCHER.Actor.Stat.Int:', w.Actor['Stat.Int']);
console.log('WITCHER.Actor.DerStat.HP:', w.Actor['DerStat.HP']);
console.log('WITCHER.skills.awareness:', JSON.stringify(w.skills.awareness));
console.log('WITCHER.Diagram.Novice:', w.Diagram.Novice);
console.log('WITCHER.Spell.Witcher:', w.Spell.Witcher);
console.log('Valid JSON: OK');
