const fs = require('fs');

const prompts51 = [
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Aard witcher sign, a concentrated telekinetic blast of rippling blue force and swirling compressed air, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Aard Sweep witcher sign, an outward expanding 360-degree shockwave of rippling blue telekinetic force, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Aard Strike witcher sign, a directed beam of devastating telekinetic blue force cracking the air, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Heliotrop witcher sign, a protective warding sigil glowing with pale translucent arcane energy absorbing kinetic impacts, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Igni witcher sign, a fierce cone of roaring orange and crimson fire crackling with intense heat, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Igni Fire Stream witcher sign, a continuous concentrated beam of white-hot melting fire and flying embers, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Igni Heatwave witcher sign, an intense radial burst of scorching heat and shimmering distorted air, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Quen witcher sign, a crackling spherical shield of protective golden-yellow arcane lightning, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Quen Active Shield witcher sign, a sustained glowing golden energy bubble deflecting incoming attacks with bright sparks, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Quen Discharge witcher sign, an exploding golden shield violently releasing stored lightning energy outwards, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Somne witcher sign, a hypnotic swirling mist of soothing pale violet sleep magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Yrden witcher sign, a glowing purple magical trap inscribed on the ground pulsing with binding energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Yrden Magic Trap witcher sign, a complex array of glowing purple runes shooting arcs of slowing arcane lightning, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Axii witcher sign, a mesmerizing triangle of glowing white and pale green mind-control magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Axii Puppet witcher sign, intense glowing white arcane strings manipulating a phantom mind, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Curse of the Evil Eye, a sinister floating ethereal eye radiating malevolent crimson energy and bad luck, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Curse of the Beast, swirling black magic revealing the spectral howling silhouette of a savage wolf, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Curse of Hunger, a withered ethereal maw surrounded by decaying shadows and green famine magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Curse of Bad Luck, a twisted web of dark chaotic energy and broken mirror shards floating ominously, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Curse of Transformation, swirling purple and black arcane energies violently twisting phantom flesh and bone, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts52 = [
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Curse of Shadows, deep oppressive unnatural darkness bleeding out like liquid smoke, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Blood Curse, boiling drops of cursed crimson blood forming a sinister glowing rune, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Agony Hex, jagged needles of invisible psychic pain glowing with malicious red energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Beguiling Hex, a deceptive shimmering pink aura hiding a sinister coercive magical compulsion, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Nightmare Hex, swirling dark violet mists taking the shape of terrifying phantoms, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Infatuation Hex, obsessive swirling magenta magic binding an ethereal chained heart, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Hex of Malice, pure concentrated negative energy forming a dark suffocating aura, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Evil Eye Hex, a glaring toxic green ethereal eye imposing sudden misfortune, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Misfortune Hex, chaotic tangled strings of dark magic disrupting fate, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Doom Hex, heavy oppressive black clouds of cursed energy bringing inevitable ruin, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Warts Hex, bubbling acidic green magic inflicting boils and festering skin, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Adre Hex, a sharp dark magical spike causing intense sudden pain, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Ana Hex, suffocating pale magic sapping breath and vitality, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Aras Hex, creeping shadow magic inflicting lethargy and weakness, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Caer Hex, sharp invisible magical thorns wrapping around a phantom limb, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Cen Hex, a blinding flash of dark energy clouding the senses, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Cors Hex, cursed necrotic energy causing sudden internal illness, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Cwyn Hex, a heavy oppressive arcane weight crushing down with dark magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Eige Hex, buzzing erratic dark magic inflicting confusion and chaos, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Gwal Hex, razor-sharp cursed winds causing mysterious bleeding, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts53 = [
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Gwer Hex, chilling dark frost magic numbing the flesh, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Gwyth Hex, searing phantom fire magic causing burning phantom pain, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Llych Hex, a sudden blast of disorienting dark chaotic force, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Rhudd Hex, corrosive dark red magic inducing violent sickness, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Straff Hex, jagged spectral chains binding with painful dark magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Thon Hex, dense suffocating magical pressure causing sheer exhaustion, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Water Invocation, a swirling pure stream of life-giving blue elemental water, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Woodland Allies Invocation, glowing ethereal silhouettes of forest animals arriving to aid, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Friendship Invocation, a warm golden aura of trust and peaceful nature magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Air Invocation, a concentrated swirling vortex of pure white elemental wind, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Listen to the Earth Invocation, glowing green roots connecting to the ground to receive ancient vibrations, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Water Walk Invocation, ethereal lily pads of glowing blue magic creating a solid path over water, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Flesh and Bone Invocation, intense emerald healing magic knitting together wounds and restoring life, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Command Animals Invocation, a pulsing crown of primal green magic asserting dominance over beasts, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of Druidic Communication, whispering wind currents carrying glowing green messages through the leaves, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Control Weather Invocation, swirling miniature storm clouds, lightning, and rain shaped by druidic will, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Create Fire Invocation, a spontaneous spark erupting into a warm controlled orange campfire, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Rapid Growth Invocation, magical vines and blooming flora violently bursting from the earth in seconds, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Heart of Stone Invocation, thick impenetrable rocky armor forming from raw earth magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Noon's Gift Invocation, a blinding beam of pure warm sunlight bringing holy protection and clarity, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

function updateHtmlFile(filePath, newPrompts) {
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    return;
  }
  let content = fs.readFileSync(filePath, 'utf8');
  let promptIndex = 0;
  
  content = content.replace(/<div class="prompt-box"[^>]*>([\s\S]*?)<\/div>\s*<button onclick="copyToClipboard\('(.*?)', this\)">Copia Prompt<\/button>/g, (match, oldDivContent, oldBtnContent) => {
    if (promptIndex < newPrompts.length) {
      const newPrompt = newPrompts[promptIndex];
      const escapedPrompt = newPrompt.replace(/'/g, "\\'");
      const newMatch = match
        .replace(oldDivContent, newPrompt)
        .replace(oldBtnContent, escapedPrompt);
      promptIndex++;
      return newMatch;
    }
    return match;
  });
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

updateHtmlFile('scratch/prompts_batch_51.html', prompts51);
updateHtmlFile('scratch/prompts_batch_52.html', prompts52);
updateHtmlFile('scratch/prompts_batch_53.html', prompts53);
