const fs = require('fs');

const prompts45 = [
  "Digital painting viewed from directly above, top-down perspective, a Forager's Guide, a thick weathered leather-bound book with pressed leaves and dried herbs sticking out of the pages, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Medical Censer crafted from polished brass, emitting soothing aromatic smoke of healing herbs and incense, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a pair of sturdy Wagon Lanterns made of thick dark iron and reinforced glass, casting a warm amber glow, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Book of Tales, an ornate thick tome bound in rich dark leather with subtle gold foil fairy tale motifs, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Camouflage Cloak, intricately woven from mottled green and brown woodland fabrics, animal furs, and artificial leaves, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a set of Crossbow Upgrades, featuring precision-crafted brass sights, a heavy iron cranking mechanism, and reinforced strings, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a weathered leather Waterskin with a sturdy wooden stopper and a coarse hemp carrying strap, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the legendary Sunstone, an exquisite elven artifact resembling a glowing pale gemstone radiating ethereal brilliant sunlight, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Potestaquisitor magical detector, an intricate brass and glass gnomish device with glowing dials and spinning arcane gyros, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Basic Prosthetic, a simple but sturdy wooden peg leg and thick leather strapping reinforced with rusted iron bands, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Witcher Prosthetic, an advanced functional mechanical arm crafted from dark steel and reinforced leather with articulated joints and hidden weapon slots, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Focus Prosthetic, an intricate mechanical limb embedded with a large glowing blue arcane crystal designed to channel magic, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Magic Prosthetic, an ethereal floating limb made of segmented dark steel pieces held together by swirling blue arcane energy, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a pair of heavy Spare Wheels for a wagon, forged from thick Mahakaman oak with sturdy dark iron rims, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a Basic Wheelchair, featuring ink blueprints of wooden frames, leather seats, and simple iron wheels, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an ancient parchment crafting schematic detailing the construction of a Quality Wheelchair, featuring complex ink diagrams of brass gears, suspension springs, and cushioned seating, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a mastercrafted Manticore School shield, forged from thick dark iron and hardened wood featuring a menacing manticore crest and alchemical bandoliers, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Basic Wheelchair, crafted from sturdy rough-hewn wood with heavy iron-rimmed wheels and practical leather straps, resting on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a finely crafted Quality Wheelchair, featuring polished dark wood, comfortable dark velvet cushions, and intricate brass gear mechanisms, resting on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Trapped Lock, a heavy iron padlock concealing a deadly spring-loaded poisoned needle mechanism within its keyhole, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts46 = [
  "Digital painting viewed from directly above, top-down perspective, a mastercrafted Manticore School witcher steel sword, featuring a robust utilitarian crossguard, a leather-wrapped hilt, and a razor-sharp steel blade, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a heavy Bear School witcher steel sword, featuring a brutal thick dark steel blade, a sturdy leather grip, and a pommel shaped like a roaring bear, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a sleek Viper School witcher steel sword, featuring an elegant twin snake motif crossguard and a deadly sharp steel blade, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a mastercrafted Viper School witcher silver sword, gleaming silver blade dripping with subtle venomous green magic, twin snake motif hilt, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, an exquisite Elven Musical Instrument, a delicate stringed lute crafted from pale silvery wood with intricate swirling leaf carvings, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Coin Clipper tool, a small precise brass and dark steel mechanical device used by thieves to shave the edges off coins, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, a Portable Strategy Table, featuring an unrolled parchment map of the Continent on a folding wooden board with carved wooden troop markers, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Aerokinesis, swirling violent gusts of white and grey wind currents manipulating small floating stones, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of an Aura of Fear, terrifying waves of dark purple and black psychic energy radiating outwards like shadows, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Calm Animals spell, soothing ripples of warm golden and pale green druidic energy floating peacefully, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Cryokinesis, jagged freezing ice crystals and swirling freezing pale blue mists, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Fortify spell, a glowing ethereal shield composed of geometric golden arcane energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Geokinesis, heavy floating rocks and chunks of dark earth levitating in a swirl of brown magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Enhance Weapon spell, a dark steel sword hovering and coated in intense crackling blue arcane energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of a Minor Illusion, a small shimmering semi-transparent ethereal butterfly glowing with pink magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Sense Poison spell, ominous toxic green glowing fumes rising from a hovering iron goblet, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Swift Feet spell, ethereal swirling wind currents wrapping around a pair of worn leather boots, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Pigment spell, vibrant splashes of magically shifting colors floating like bright liquid light, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Pyrokinesis, a fierce roaring vortex of dark orange and crimson arcane flames, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the Green Thumb spell, rapidly blooming magical vines and bright glowing flowers bursting with green life energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

const prompts47 = [
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of the See Aura spell, a glowing ethereal third eye revealing vibrant spectrums of psychic energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Controlled Summoning, a perfectly drawn geometric summoning circle glowing with stable crimson Goetia runes, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the magical manifestation of Uncontrolled Summoning, a shattered and scorched summoning circle exploding with violent chaotic dark demonic energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Goat's Mantle Ritual, a bloody goat pelt surrounded by sinister chalk runes and melted black candles, lying flat on a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Ritual of the Name, an ancient parchment burning with eerie green fire while a silver pendulum swings above it, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the dark manifestation of the Ritual of Binding, complex interlocking Goetic circles glowing with oppressive dark red demonic energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of a Blessed Weapon, a hovering steel longsword suffused with blinding pure white holy light, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Feast of Abundance, a magical array of glowing ethereal fruits and bread materializing from golden light, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Blessing of Abundance, shimmering golden rain and glowing stalks of wheat radiating holy energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Champion of the River, swirling torrents of deep blue water taking the shape of a protective water elemental, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Seek the Seekers invocation, glowing ethereal silver threads acting as a magical compass pointing the way, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of the Mother's Conspiracy, dark twisting roots and spectral ravens whispering ancient woodland secrets, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of Herbalism magic, a patch of rare medicinal herbs rapidly growing and glowing with intense emerald life energy, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of False Darkness, an unnatural deep magical shadow actively consuming the surrounding light, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of Bigelow's Impurity, a creeping toxic rot and dark green corruption spreading with cursed magic, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the druidic manifestation of Nature's Wrath, a violent swirling storm of razor-sharp thorns and crackling green lightning, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of Divine Inspiration, a radiant halo of warm golden light exuding hope and courage, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of Silver Light, a brilliant and piercing pure silver holy light burning away dark shadows, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Light of Penance, a heavy oppressive beam of judging crimson and gold holy fire, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus.",
  "Digital painting viewed from directly above, top-down perspective, the divine manifestation of the Blessed Herd, ethereal glowing animal spirits running in a stampede guided by bright divine will, hovering over a dark rough textured stone surface, large subject perfectly framed with narrow margins, filling the space without overflowing, dark fantasy style, Witcher universe aesthetic, moody lighting, high contrast, 1024x1024, sharp focus."
];

function updateHtmlFile(filePath, newPrompts) {
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    return;
  }
  let content = fs.readFileSync(filePath, 'utf8');
  let promptIndex = 0;
  
  content = content.replace(/<div class="prompt-box"[^>]*>([\s\S]*?)<\/div>\s*<button onclick="copyToClipboard\('(.*?)', this\)">Copia Prompt<\/button>/g, (match, oldDivContent, oldBtnContent) => {
    if (promptIndex < newPrompts.length) {
      const newPrompt = newPrompts[promptIndex];
      const escapedPrompt = newPrompt.replace(/'/g, "\\'");
      const newMatch = match
        .replace(oldDivContent, newPrompt)
        .replace(oldBtnContent, escapedPrompt);
      promptIndex++;
      return newMatch;
    }
    return match;
  });
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

updateHtmlFile('scratch/prompts_batch_45.html', prompts45);
updateHtmlFile('scratch/prompts_batch_46.html', prompts46);
updateHtmlFile('scratch/prompts_batch_47.html', prompts47);
